'use client';

import React from 'react';
import { FileCheck, Download, GitCommit, Lock, Lightbulb } from 'lucide-react';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import Badge from '@/components/ui/Badge';
import { downloadTextFile } from '@/lib/utils';
import { useToast } from '@/components/providers/ToastProvider';

export interface ChangeRecord {
  id: string;
  changeSetId: string;
  orgAlias: string;
  orgId: string;
  intent: string;
  businessRationale: string;
  approverIdentity: string;
  deploymentId: string;
  gitCommitHash: string;
  signatureHash: string;
  createdAt: string;
  // Governance evidence (PRD Hard Rule 1) — the record ships with the blast
  // radius, gate outcomes, skills used, and the dry-run reference.
  dryRunId?: string | null;
  impactBrief?: {
    blastRadiusClassification?: string;
    dependencyImpact?: { referencingComponentsCount?: number };
    dataImpact?: { violatingRecordsCount?: number };
  } | null;
  gateResults?: Array<{ gateCode: string; outcome: string; plainLanguageReason?: string }> | null;
  skillsUsed?: string[];
}

interface ChangeRecordCardProps {
  record?: ChangeRecord;
}

/** Builds a portable, tamper-evident markdown rendering of the record. */
function buildChangeRecordMarkdown(record: ChangeRecord): string {
  return [
    `# Forge Change Record: ${record.id}`,
    '',
    '| Field | Value |',
    '| --- | --- |',
    `| Change Set ID | ${record.changeSetId} |`,
    `| Target Environment | ${record.orgAlias} (\`${record.orgId}\`) |`,
    `| Approver Identity | ${record.approverIdentity} |`,
    `| Deployment ID | ${record.deploymentId} |`,
    `| Git Commit Reference | ${record.gitCommitHash} |`,
    `| Created At | ${record.createdAt} |`,
    '',
    '## Intent',
    record.intent,
    '',
    '## Business Rationale',
    record.businessRationale,
    '',
    '## SHA-256 HMAC Signature',
    '```',
    record.signatureHash,
    '```',
    '',
    '---',
    '_Generated by Forge. Tamper-evident governance record._',
    '',
  ].join('\n');
}

export default function ChangeRecordCard({ record }: ChangeRecordCardProps) {
  const defaultRecord: ChangeRecord = {
    id: 'CR-2026-001',
    changeSetId: 'cs_88391',
    orgAlias: 'Dev2 Sandbox',
    orgId: '00D800000001ABC',
    intent: 'Create ValidationRule Require_Loss_Reason_On_Closed_Lost on Opportunity',
    businessRationale: 'Enforces mandatory win/loss analysis compliance requested by VP of Sales Ops.',
    approverIdentity: 'governance-lead@enlightlab.com',
    deploymentId: '0Af8000000abc99',
    gitCommitHash: 'git:7f9a11b0e2',
    signatureHash: 'sha256:8f2a110a7b4c9e123456789abcdef0123456789abcdef0123456789abcdef0',
    dryRunId: '0Af8000000abc01',
    impactBrief: {
      blastRadiusClassification: 'Low',
      dependencyImpact: { referencingComponentsCount: 0 },
      dataImpact: { violatingRecordsCount: 0 },
    },
    gateResults: [
      { gateCode: 'REF-01', outcome: 'PASS' },
      { gateCode: 'REF-07', outcome: 'PASS' },
    ],
    skillsUsed: ['platform-validation-rule-generate'],
    createdAt: '2026-07-31T09:30:00Z',
  };

  const activeRecord = record || defaultRecord;
  const skillsUsedList = activeRecord.skillsUsed || [];
  const toast = useToast();

  return (
    <Card variant="glass" className="space-y-6 border-emerald-300 bg-emerald-50/20 p-6 md:p-8">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-brand-border pb-4">
        <div className="space-y-1.5">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="inline-flex items-center gap-1.5 text-xs font-mono font-bold uppercase tracking-[0.14em] text-emerald-700">
              <FileCheck className="w-3.5 h-3.5 text-emerald-600" />
              STAGE 10: TAMPER-EVIDENT AUDIT RECORD
            </span>
            <Badge variant="pass" isMono size="sm">
              SHA-256 HMAC VERIFIED
            </Badge>
          </div>
          <h2 className="text-2xl font-bold tracking-tight text-brand-dark flex items-center gap-2">
            {activeRecord.id}
          </h2>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            leftIcon={<Download className="w-3.5 h-3.5" />}
            onClick={() => {
              downloadTextFile(
                `forge-change-record-${activeRecord.id}.md`,
                buildChangeRecordMarkdown(activeRecord),
                'text/markdown'
              );
              toast.success('Change record exported', 'Markdown (.md) download started.');
            }}
          >
            Export .md
          </Button>
          <Button
            variant="primary"
            size="sm"
            leftIcon={<Download className="w-3.5 h-3.5" />}
            onClick={() => {
              downloadTextFile(
                `forge-change-record-${activeRecord.id}.json`,
                JSON.stringify(activeRecord, null, 2),
                'application/json'
              );
              toast.success('Change record exported', 'JSON (.json) download started.');
            }}
          >
            Export .json
          </Button>
        </div>
      </div>

      {/* In plain English — what the signed record is and why it matters */}
      <div className="p-4 rounded-xl bg-blue-50/70 border border-blue-200/70 space-y-3">
        <div className="flex items-center gap-2">
          <Lightbulb className="w-4 h-4 text-brand-blue shrink-0" />
          <span className="text-xs font-bold uppercase tracking-[0.12em] text-brand-blue">In plain English</span>
        </div>
        <div className="space-y-2.5 text-xs text-slate-600 leading-relaxed">
          <p>
            <span className="font-bold text-brand-dark">What this does:</span>{' '}
            After your change is live, Forge writes down everything that happened: what
            changed, why, who approved it, the results of every safety check, and the
            deployment reference. Then it seals the record with a digital signature (HMAC-SHA256).
            The signed record is saved to your audit trail and pushed to your GitHub
            repository (or stored locally if no GitHub is connected).
          </p>
          <p>
            <span className="font-bold text-brand-dark">Why it matters:</span>{' '}
          </p>
          <ul className="space-y-1.5 pl-1">
            <li>• Tamper-evident: the signature only matches the record&apos;s exact content. If anyone edits the record later, the signature breaks and the tampering is visible.</li>
            <li>• Full accountability: every org change has an owner, a reason, and proof. Auditors, compliance, and future admins can see exactly who changed what and why.</li>
            <li>• Durable history: GitHub keeps a browsable, versioned log of every governed change your team makes.</li>
          </ul>
          <p>
            <span className="font-bold text-brand-dark">What you need to do:</span>{' '}
            Nothing. This runs automatically after a successful deployment. You can review
            the record here, copy the signature hash, and export it as .md or .json for
            your own records.
          </p>
        </div>
      </div>

      {/* Record Fields Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-mono">
        <div className="p-3 bg-white rounded-xl border border-brand-border space-y-1 shadow-soft">
          <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wide">Target Environment</span>
          <span className="block font-bold text-brand-dark">
            {activeRecord.orgAlias} ({activeRecord.orgId})
          </span>
        </div>

        <div className="p-3 bg-white rounded-xl border border-brand-border space-y-1 shadow-soft">
          <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wide">Approver Identity</span>
          <span className="block font-bold text-emerald-700">
            {activeRecord.approverIdentity}
          </span>
        </div>

        <div className="p-3 bg-white rounded-xl border border-brand-border space-y-1 shadow-soft">
          <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wide">Deployment ID</span>
          <span className="block font-bold text-brand-blue">
            {activeRecord.deploymentId}
          </span>
        </div>

        <div className="p-3 bg-white rounded-xl border border-brand-border space-y-1 shadow-soft">
          <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wide flex items-center gap-1">
            <GitCommit className="w-3.5 h-3.5 text-brand-blue" />
            Git Commit Reference
          </span>
          <span className="block font-bold text-brand-dark">
            {activeRecord.gitCommitHash}
          </span>
        </div>
      </div>

      {/* Rationale & Intent Summary */}
      <div className="p-4 bg-white rounded-xl border border-brand-border space-y-2 text-xs shadow-soft">
        <div>
          <span className="text-[10px] font-mono uppercase font-bold text-slate-500">
            Intent Statement:
          </span>
          <p className="font-semibold text-brand-dark">{activeRecord.intent}</p>
        </div>
        <div>
          <span className="text-[10px] font-mono uppercase font-bold text-slate-500">
            Business Rationale:
          </span>
          <p className="text-slate-600 font-mono text-[11px]">{activeRecord.businessRationale}</p>
        </div>
      </div>

      {/* Governance Evidence (Hard Rule 1) */}
      {(skillsUsedList.length > 0 || activeRecord.impactBrief || activeRecord.gateResults?.length || activeRecord.dryRunId) && (
        <div className="p-4 bg-white rounded-xl border border-brand-border space-y-3 shadow-soft">
          <span className="text-[10px] font-mono uppercase font-bold text-slate-500 block">
            Governance Evidence
          </span>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs font-mono">
            <div className="p-2 rounded-lg bg-brand-surface/70 border border-brand-border">
              <span className="block text-[10px] text-slate-500 uppercase font-bold">Blast Radius</span>
              <span className="font-bold text-brand-dark">
                {activeRecord.impactBrief?.blastRadiusClassification || 'N/A'}
              </span>
            </div>
            <div className="p-2 rounded-lg bg-brand-surface/70 border border-brand-border">
              <span className="block text-[10px] text-slate-500 uppercase font-bold">Referencing</span>
              <span className="font-bold text-brand-dark">
                {activeRecord.impactBrief?.dependencyImpact?.referencingComponentsCount ?? 'N/A'}
              </span>
            </div>
            <div className="p-2 rounded-lg bg-brand-surface/70 border border-brand-border">
              <span className="block text-[10px] text-slate-500 uppercase font-bold">Violating Records</span>
              <span className="font-bold text-brand-dark">
                {activeRecord.impactBrief?.dataImpact?.violatingRecordsCount ?? 'N/A'}
              </span>
            </div>
            <div className="p-2 rounded-lg bg-brand-surface/70 border border-brand-border">
              <span className="block text-[10px] text-slate-500 uppercase font-bold">Gates</span>
              <span className="font-bold text-brand-dark">
                {activeRecord.gateResults?.length
                  ? `${activeRecord.gateResults.filter((g) => g.outcome === 'REFUSED').length} refused / ${activeRecord.gateResults.length} evaluated`
                  : 'N/A'}
              </span>
            </div>
          </div>
          {(skillsUsedList.length > 0 || activeRecord.dryRunId) && (
            <div className="flex flex-wrap items-center gap-2 text-[10px] font-mono">
              {skillsUsedList.length > 0 && (
                <span className="text-slate-500">
                  Skills: {skillsUsedList.join(', ')}
                </span>
              )}
              {activeRecord.dryRunId && (
                <span className="text-slate-500">Dry-Run: {activeRecord.dryRunId}</span>
              )}
            </div>
          )}
        </div>
      )}

      {/* SHA-256 HMAC Signature Box */}
      <div className="p-4 rounded-xl bg-slate-900 text-slate-200 font-mono text-xs space-y-2 border border-slate-800">
        <div className="flex items-center justify-between text-slate-400 border-b border-slate-800 pb-2">
          <span className="flex items-center gap-1.5 text-emerald-400 font-bold text-[11px]">
            <Lock className="w-3.5 h-3.5 text-emerald-400" />
            SHA-256 HMAC SIGNATURE HASH
          </span>
          <span className="text-[10px] text-slate-500">Tamper-Evident Integrity OK</span>
        </div>
        <p className="text-[11px] text-emerald-300 break-all select-all leading-relaxed">
          {activeRecord.signatureHash}
        </p>
      </div>
    </Card>
  );
}
